# Generated by Django 6.0.3 on 2026-03-30 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intervention_type', models.CharField(choices=[('parent-contact', 'Parent Contacted'), ('counseling', 'Counseling Session'), ('tutoring', 'Extra Tutoring'), ('meeting', 'Teacher-Student Meeting'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in-progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_interventions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
