# Generated by Django 6.0.3 on 2026-03-29 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(help_text='0-100 probability of being at-risk')),
                ('risk_level', models.CharField(choices=[('green', 'Safe'), ('yellow', 'Moderate Risk'), ('red', 'High Risk')], max_length=20)),
                ('attendance_pct', models.FloatField(default=0)),
                ('grade_avg', models.FloatField(default=0)),
                ('assignments_missed', models.IntegerField(default=0)),
                ('top_factors', models.JSONField(blank=True, default=list)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='students.student')),
            ],
            options={
                'ordering': ['-scored_at'],
            },
        ),
    ]
